### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Jackie-LJQ** [c00kie17/liquipediapy#5]
Hello. I want to get the player data of cs from liquipedia. I don't have an 'appname'. I just want some data to analyse, like the player's name, which team they playing for, etc., on my local PC.
I try to use request.get() in python, but it returns the information of the whole page. I also try to pass some parameters in URLs but I don't know what is the valiad keys in liquipedia
Do you have any suggestions what should I do??
Thank you very much.
Also I am really new to API. Sorry if the question is trival.

**Comment by c00kie17** [comment]
Hi. 
Sorry for the late reply I needed to fix some updates to the package that were broken in Pypi 
About the `appname` , you need to provide one due to liquipedia's terms of service they use to identify the requests you make and the fequency you make it at. The good thing is it doesn't need to be anything important you can just use something like `mycsdatagrabber`

**Initilize liquidpedia csgo object**

```
from liquipediapy import counterstrike


counterstrike_obj = counterstrike("mycsdatagrabber")
```

**To grab details of a player you can do**
```
player_details = counterstrike_obj.get_player_info('nitr0',True)
```

This should have the team they play for too 

I have updated the package to version **2.1.0** please update using the command 
`pip install --upgrade  liquipediapy`
